"""Claim ORM model.

Claims are auto-generated by the event engine when a parametric trigger fires.
They are NOT manually filed by workers — this is a core design principle of
parametric insurance.  Each claim links to a disruption event and records the
computed payout amount.
"""

import uuid
from datetime import datetime

from sqlalchemy import DateTime, Float, ForeignKey, String, Text, func
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.database import Base


class Claim(Base):
    """Auto-generated parametric insurance claim."""

    __tablename__ = "claims"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    worker_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("workers.id"), nullable=False, index=True
    )
    policy_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("policies.id"), nullable=False, index=True
    )

    # Claim type is ALWAYS income_loss — enforced at schema level
    claim_type: Mapped[str] = mapped_column(
        String(30), nullable=False, default="income_loss"
    )
    event_type: Mapped[str] = mapped_column(
        String(50), nullable=False
    )  # rainfall / aqi / curfew_strike
    event_severity: Mapped[str] = mapped_column(
        String(20), nullable=False
    )  # low / medium / high / critical
    event_description: Mapped[str | None] = mapped_column(Text, nullable=True)

    status: Mapped[str] = mapped_column(
        String(20), nullable=False, default="pending"
    )  # pending / approved / rejected / paid
    payout_amount_inr: Mapped[float] = mapped_column(Float, nullable=False, default=0.0)
    fraud_flag: Mapped[str | None] = mapped_column(
        String(100), nullable=True
    )  # null = clean, otherwise describes the flag

    triggered_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )

    # Relationships
    worker = relationship("Worker", back_populates="claims")
    policy = relationship("Policy", back_populates="claims")
    payout = relationship("Payout", back_populates="claim", uselist=False, lazy="noload")
